version: 2.1

orbs:
  maven: circleci/maven@1.0.1
  heroku: circleci/heroku@1.0.1

workflows:
  build: # build, test, resolve dependencies, and deploy if branch is master
    jobs:
      - maven/test:
          settings_file: ".circleci/settings.xml"
  earlymorning: # build and deploy master at the crack-o-dawn
    triggers:
      - schedule:
          cron: "0 10 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - maven/test:
          settings_file: ".circleci/settings.xml"
      - heroku/deploy-via-git:
          requires:
            - maven/test
